# =====================
# Global
# =====================
global:
  domain: example.com
  storageClass: standard

# =====================
# Grafana
# =====================
grafana:
  enabled: false

# =====================
# Loki
# =====================
loki:
  enabled: false

# =====================
# Tempo
# =====================
tempo:
  enabled: false

# =====================
# MinIO (Object Storage)
# =====================
minio:
  enabled: true

  mode: standalone

  rootUser: minio
  rootPassword: minio123

  persistence:
    enabled: true
    size: 100Gi
    storageClass: standard

  buckets:
    - name: thanos
      policy: none
      purge: false

# =====================
# Thanos
# =====================
thanos:
  enabled: true

  objstoreConfig:
    type: s3
    config:
      bucket: thanos
      endpoint: minio:9000
      access_key: minio
      secret_key: minio123
      insecure: true
